lensapp/lens-platform-sdk

src/InvitationService.ts
In ORMs the expiryTime might be a `Date`. This makes it easier for end users to call the Permission service with ORM datatypes.
=> Make expiryTime orm-compatible

src/K8sCluster.ts
This property doesn't actually exist.
=> Remove ownerId from K8sCluster

src/Permissions.test.ts, src/Permissions.ts, src/PermissionsService.ts, src/index.ts
* Add permission check for deleting clusters.
* Deprecate canI. Please use canSpace from now on. canI will be removed at a later time.
* Export new `K8sClusterActions`
=> Add permission check for deleting clusters. Deprecate canI.

src/UserService.ts
At the moment the backend is ignoring the username in the endpoint. However, we should differentiate between the current username (here in the username function parameter) and the (optional) updated username in the `user` object.
This allows us later to refactor the backend to make email property optional in the user object, and use the username in the endpoint instead.
=> Make updating username work properly.

.github/workflows/build.yaml, .github/workflows/test.yaml, package-lock.json, tsconfig.json
Remove `rootDir` as we are now have `integration-test` at root also, also add a new CI to check if build pass
If we keep `rootDir`, `npm run build` will throw
```
error TS6059: File '/Users/hchen/lens-platform-sdk/integration-test/SpaceService.test.ts' is not under 'rootDir' '/Users/hchen/lens-platform-sdk/src'. 'rootDir' is expected to contain all source files.
The file is in the program because:
Matched by include pattern '**/*' in 'tsconfig.cjs.json'
error TS6059: File '/Users/hchen/lens-platform-sdk/integration-test/UserService.test.ts' is not under 'rootDir' '/Users/hchen/lens-platform-sdk/src'. 'rootDir' is expected to contain all source files.
The file is in the program because:
Matched by include pattern '**/*' in 'tsconfig.cjs.json'
error TS6059: File …
```
=> Make build pass

src/Permissions.test.ts, src/Permissions.ts
* Fixes #66 
* Bug #66 causes member to be "None" if extension would remove it's own implementation of the Role check (which has a different implementation)
=> Fix Role check in Space

tsconfig.cjs.json, tsconfig.esm.json
`rootDir` was removed from `tsconfig.json` in this PR https://github.com/lensapp/lens-platform-sdk/pull/65 but that creates a regression for published npm module become `src/index.d.js` instead of `./index.d.js` at the root.
User will get `"Cannot find module 'lens-platform-sdk' or its corresponding type declarations.ts(2307)"` error
This PR should fix the isssue.
=> Export type

src/UserService.ts, src/exceptions/utils.ts
Integration tests are going to be added as soon as the relevant changes are merged to Lens Platform. I'm planning only to add tests for unsuccessful user deletion (exceptional cases), - since user creation via SDK is not supported yet, I don't see any way of testing successful user deletion idempotently.
=> Implement a function for deleting a user

src/UserService.ts
Getting this
when upgrade sdk from 0.0.1 to 4.0.3 in backend, I think we don't need to be that strict about `userAttributes.name`
=> Change userAttributes.name to just 'string'

src/InvitationDomain.ts, src/InvitationService.ts, src/K8sCluster.ts, src/Permissions.ts, src/PermissionsService.ts, src/SpaceService.ts, src/TeamService.ts, src/index.ts, src/types/types.ts
* Add and export Entity types
* Add type helper for creating Entity types
* SDK will now have separate types for "Dto" types and database Entity types
* Permission service will accept both for easier usage
* Fix Invitation createdAt type 
Maybe in the future we can improve the conditional mapped type to autoconvert e.g. "Space" to "SpaceEntity" in the interface.
=> Add Entity types

package-lock.json, package.json
so `@types/pino` will be installed when installing sdk, so user of sdk won't get `TS7016: Could not find a declaration file for module 'pino'` if not include `@types/pino` in their dependencies.
=> Move @types/pino to dependencies

README.md, integration-test/UserService.test.ts, integration-test/utils.ts, package.json, src/LensPlatformClient.test.ts, src/LensPlatformClient.ts, src/Permissions.test.ts, src/PermissionsService.ts, src/UserService.ts
- The caller might want to provide the access token for the sdk asynchronously, which could handle e.g. refreshing an expired token before returning it. This is accomplished by making `getAccessToken` async.
- This is a major breaking change.
- I decided to remove currentUserId, because we don't want to make that async. Note that this (default) is also removed from the Permission classes.
Seems to work okay in the extension.
=> async get access token

src/Permissions.test.ts, src/Permissions.ts
Add new action for changing billing plans - needs to be Space Owner.
Signed-off-by: Steve Richards <srichards@mirantis.com>
=> Add new action to restrict Space plan changes to owners

src/K8sCluster.ts, src/index.ts
* Follow up to https://github.com/lensapp/lens-platform-sdk/pull/156
* Export types
* Use Phase type in K8sCluster
* Use lowerCase capitalization for "non-CRD" Phases for now
=> Export Phase. Tune Phase capitalization.

package-lock.json, package.json, src/BillingPageTokenService.ts, src/CatalogAPI.ts, src/Exceptions.test.ts, src/InvitationService.ts, src/LensPlatformClient.test.ts, src/LensPlatformClient.ts, src/Permissions.test.ts, src/Permissions.ts, src/Space.test.ts, src/SpaceService.ts, src/TeamService.ts, src/User.test.ts, src/UserService.ts, src/exceptions/common.exceptions.ts, src/exceptions/team.exceptions.ts, src/exceptions/utils.ts, src/index.ts
- Disable `@typescript-eslint/naming-convention` > will introduce breaking changes if enable this.
- Disable `@typescript-eslint/ban-ts-comment` > I think it's ok to add `@ts-expect-error`...
- Disable `@typescript-eslint/no-unsafe-assignment` > This is not easy to fix, as `any` often leaks from dependencies (e.g. `axois` uses lots of `any`).
- Disable `no-warning-comments` > Just annoying.
=> Update dependencies, fix lint errors from updated lint rules

package-lock.json, src/InvitationService.ts, src/SpaceService.ts, src/UserService.ts, src/exceptions/utils.ts
As 400 messages can be in many formats, let's return whatever backend return in `body.message`, instead of hardcoded message. And also includes the original (axios) exception for easier debugging.
Closes https://github.com/lensapp/lens-platform-sdk/issues/130
=> When 400, return whatever backend returned

src/Permissions.test.ts, src/Permissions.ts
This should be used for patch permission check instead of the access action. The business logic / authorization rules are identical.
=> Add PatchK8sCluster permission check

README.md, src/LensPlatformClient.ts
Part of the "enterprise proxy" support for Lens/Lens ID.
=> Allow to pass (optional) httpAgent/httpsAgent to axios

integration-test/UserService.test.ts, src/UserService.ts, src/index.ts
We need to display company name for the subscription. This is unavailable for Lens Business ID case, so it's added to subscription info.
=> Add company name to SubscriptionInfo

integration-test/UserService.test.ts, src/exceptions/common.exceptions.ts
The captureStackTrace is not available yet in Safari and Firefox
=> Check if captureStackTrace is available before calling

src/UserService.ts, src/exceptions/user.exceptions.ts
We don't want the default "Conflict" message in the UI.
=> Pass error message for SubscriptionAlreadyExistsException

src/BusinessService.ts
Related to https://github.com/lensapp/lenscloud/issues/2025.
POST for https://github.com/lensapp/lenscloud/blob/21a9c8e2cd0af0ae7718a93bc1e27657565e3052/backend/src/modules/business/business-subscriptions.controller.ts#L64
PATCH for
https://github.com/lensapp/lenscloud/blob/21a9c8e2cd0af0ae7718a93bc1e27657565e3052/backend/src/modules/business/business-subscriptions.controller.ts#L91
We can add tests when all CRUD is done for business so we can clear the state after tests
=> Business subscription activate/deactivate

src/BusinessService.ts
Seems we have `state` in the response body, but sdk missing this property.
Requires for https://github.com/lensapp/lenscloud/issues/2072
=> Add missing 'state' to business subscription

src/UserService.ts, src/index.ts
- Add `active:boolean` to `SubscriptionSeat`
- Change the interface name `SubscriptionSeatInfo` > `SubscriptionSeat` (I think `Info` was from Recurly type, we probably don't need that, this makes variable name shorter in frontend)
=> Add `active:boolean` to SubscriptionSeat, change the name `SubscriptionSeatInfo` > `SubscriptionSeat`

src/BusinessService.ts
`external` should be set by backend.. we might need to return 400 if user tries to set `external`
=> No allowing user to set .external when create LBID

.npmignore, package.json
Fix a regression from https://github.com/lensapp/lens-platform-sdk/pull/363
I have removed `files` section in package.json, but didn't add `.npmignore` so `.gitignore` was used, `./dist` was ignored so we end up publish nothing, this PR fixes it by adding the `.npmignore` to include `./dist`.
Also fix a typo in package.json
=> Add .npmignore, fix typo in package.json

package.json
Regression from https://github.com/lensapp/lens-platform-sdk/pull/363
Editor's typescript server can't find type definition..
It seems necessary to add `types` if `main` is defined in package.json, from https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
```
If your package has a main .js file, you will need to indicate the main declaration file in your package.json file as well. Set the types property to point to your bundled declaration file.
```
=> Fixing missing type definition for the published version

package.json
`webpack@5` has `resolve.fullySpecified` default to `true` https://webpack.js.org/configuration/module/#resolvefullyspecified, this causes some issues for sdk users as our `esm` build is with `{ type: module }` but not fully follow the `esm` module spec, `webpack@5` will throw errors when a dependencies is with `{ type: module }` but not following node.js's `esm` module spec.
This PR remove adding `{ type: module }` to esm output, so we can avoid `webpack@5` exceptions.
Needed for https://github.com/lensapp/lenscloud/pull/2224
=> Don't add type:module to esm output to avoid `webpack@5` exceptions

src/UserService.ts
Adding method for the endpoint `POST /users/:username/confirm-personal-eligibility`
Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>
=> Add method for confirming personal license eligibility

src/UserService.ts
- User doesn't have to have access token to be able to call `verifySecondaryEmail`
- Change throwing Error to be instance of `LensSDKException`
=> User can verify secondary email without logged in

.github/workflows/test.yaml
Because lenscloud and lens are still using 16.
=> Test against node@16

src/BusinessService.ts
As the property is optional, used only in legacy businesses it's better to omit it from existing methods.
=> Omit subscription id from creating

src/BusinessService.ts
For https://github.com/lensapp/lenscloud/pull/2836
The email is the Recurly account contact email.
=> Add `.email` to GET parent/children response

src/index.ts
So `zod` can use it at runtime.
=> Export schema as value not type

src/BusinessService.ts
Add `.fromChildBusinessId`  which is added in https://github.com/lensapp/lenscloud/pull/2914
Also fix the interface
- Remove `isTrial` has backend never returns this key.
- Add missing `trialStartedAt`, `trialEndsAt`, `companyName` and `accountCode`
- Fix `businessAccount` (removed), should be `isBusinessAccount`
- Reorder the keys to be consistent with the interface defined in backend.
=> Add `.fromChildBusinessId` for business subscription, and fix interface

src/BusinessService.ts
Allow business admins to assign subscription seats directly.
=> Allow assign business subscription seat

README.md, package-lock.json, package.json, src/LensPlatformClient.ts
* Update axios to 1.x so that `getAdapter` is possible. `require("axios/lib/adapters/http");` was always incorrect (but happened to work)
* Adds support for properly setting httpAdapter for Node.js usage (from e.g. electron's renderer)
* Makes the sdk more compatible with esbuild
=> feat: axios 1.x

integration-test/SpaceService.test.ts
We already have integration tests in backend, and these tests will created bored clusters in staging, which need to be manually clean up (if the cleaning up logics in the tests doesn't work).
=> Remove K8sCluster integration tests

.github/workflows/dependabot-test.yaml, .github/workflows/test.yaml, integration-test/DemoClusterService.test.ts, integration-test/TeamService.test.ts, integration-test/utils.ts, jest.integration-test.config.js, src/DemoClusterService.ts, src/LensPlatformClient.ts
* Add service for getting the demo cluster
* Update Node.js to 18
* Fix integration tests not working
* Fix to not run some unit tests in integration tests
=> feat: demo cluster api

.github/workflows/lint.yaml, .github/workflows/publish.yml, integration-test/UserService.test.ts, integration-test/utils.ts, src/BusinessService.ts, src/UserService.ts
* `release/v12` is for `lens-platform-extension-sdk` `6.x` series
=> feat: publish from release/v12

src/BusinessService.ts
Removing `BusinessService.createOne` method, as this endpoint is not in use anymore
=> chore: remove create business method
