lensapp/lens-platform-sdk

src/UserService.ts

These are included when user is fetching itself.

Add user attributes to the User object

---

src/BillingPlan.ts

Introduced in https://github.com/lensapp/lenscloud/pull/637

New billing plan properties

---

src/InvitationService.ts

Related to https://github.com/lensapp/lenscloud/pull/643

Add spaceDescription to Invitation type

---

src/UserService.ts

Backend has been updated to not require email in updates.
This also allows user to update own email.

Email is optional in user update

---

src/LensPlatformClient.ts
src/PlanService.ts
src/SpaceService.ts

Related to https://github.com/lensapp/lenscloud/pull/665

Implement space plan downgrade and add plan service

---

src/LensPlatformClient.ts

Cherry picked from closed PR https://github.com/lensapp/lens-platform-sdk/pull/59 which was already approved.

Cherry-pick commits from closed PR #59

---

integration-test/InvitationService.test.ts
integration-test/UserService.test.ts
package-lock.json
src/UserService.ts
src/exceptions/common.exceptions.ts
src/exceptions/invitation.exceptions.ts
src/exceptions/user.exceptions.ts

- Refactor one "throws async" test to be simpler
- Fix typo
- Use the correct parent class for `InvalidEmailDomainException`

Add Username already exists error

---

src/InvitationService.ts

Can't add integration test yet.

Get invitation by key

---

README.md
integration-test/SpaceService.test.ts
package-lock.json
package.json
src/InvitationService.ts
src/LensPlatformClient.test.ts
src/LensPlatformClient.ts
src/OpenIdConnect.ts
src/PlanService.ts
src/SpaceService.ts
src/TeamService.ts
src/UserService.ts
src/exceptions/utils.ts

* Fixes https://github.com/lensapp/lens-platform-sdk/issues/83
* Rename the "got" property of LensPlatformClient as library independent
* Switch got to axios to support browsers

Add browser support

---

src/exceptions/common.exceptions.ts

Signed-off-by: Alex Culliere <alozhkin@mirantis.com>

Fix prototype chain in UnprocessableEntityException

---

src/LensPlatformClient.test.ts
src/LensPlatformClient.ts

* Fixes https://github.com/lensapp/lens-platform-sdk/issues/90

Allow use without token

---

src/InvitationService.ts
src/K8sCluster.ts
src/SpaceService.ts
src/TeamService.ts

- Add missing properties updatedAt/createdAt
- Remove non-existing ownerId from Space

Improve types

---

tsconfig.json

Fix "TypeError: pino_1.default is not a function" error.

Fix pino import error.

---

src/HostedTokenService.ts
src/LensPlatformClient.ts

Adds a service for fetching hosted token.

Add hosted token service to SDK

---

src/Permissions.test.ts
src/Permissions.ts

* Continuation of https://github.com/lensapp/lens-platform-sdk/pull/106

Add Permission rules for Personal Space delete/rename

---

src/SpaceService.ts

Use .put for replace, .patch for update cluster

---

src/BillingPlan.ts

Introduced in https://github.com/lensapp/lenscloud/pull/1059
Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>

Add BillingPlan invoicePreview properties

---

src/BillingPlan.ts

Signed-off-by: Hung-Han (Henry) Chen <chenhungh@gmail.com>

Add billingEnabled:boolean

---

src/BillingPlan.ts

https://github.com/lensapp/lenscloud/pull/1077

Add couponCredits to BillingPlan

---

package.json
src/Permissions.test.ts
src/Permissions.ts

Needed for this
https://github.com/lensapp/lenscloud-lens-extension/issues/961

Fix team permissions

---

src/InvitationService.ts

Add optional role property to invitation entity.

Add role to invitation

---

src/K8sCluster.ts

* Related issue https://github.com/lensapp/dev-cluster-operator/issues/101
* Related PR https://github.com/lensapp/dev-cluster-operator/pull/104

Add Reprovisioning state to DevCluster CRD

---

src/LensPlatformClient.ts

So we know who is using `getAccessToken`..

Pass url as parameter to getAccessToken

---

integration-test/UserService.test.ts
src/UserService.ts
src/exceptions/utils.ts

- add get subscription method.
- update other methods to use new endpoint url.

User subscriptions improvements

---

integration-test/UserService.test.ts
src/UserService.ts

- Add get for user billing information

Add get user billing information

---

integration-test/UserService.test.ts
src/UserService.ts

* Requires https://github.com/lensapp/lenscloud/pull/1753

Add endpoint for fetching subscription by id.

---

integration-test/UserService.test.ts
src/UserService.ts

* Requires https://github.com/lensapp/lenscloud/pull/1861

Add subscription state

---

src/BusinessService.ts
src/LensPlatformClient.ts
src/UserService.ts
src/index.ts

Related issue https://github.com/lensapp/lenscloud/issues/1912

Add type `Business`, add `getBusinesses()`/`.createOneBusiness()`

---

src/BusinessService.ts

Fixes: https://github.com/lensapp/lens-platform-sdk/issues/330

Remove timestamps & businessUsers prop from business/create

---

integration-test/UserService.test.ts

I guess subscriptions are being auto renewed on staging, so a fixed date doesn't make sense.

Change dates to `expect.any(String)`

---

src/BusinessService.ts
src/index.ts

For this endpoint `GET /businesses/:id/subscriptions` https://github.com/lensapp/lenscloud/issues/1938

Add BusinessSubscription, business.getSubscriptions(id)

---

src/BusinessService.ts
src/index.ts

Also add/export `UserBusinessRole`/`BusinessInvitationState`

Add `business.createInvitation` and types `BusinessInvitation`

---

src/BusinessService.ts

Make sure typing reflects to actually data schema.

Fields in BusinessUser can be undefined if don't have account yet

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2047

Add businessService.getInvitations() for listing business invitations

---

src/BusinessService.ts
src/UserService.ts
src/types/types.ts

getBillingPageToken service returns a token for the Recurly hosted pages when available.

345 add getBillingPageToken resource to BusinessService

---

src/UserService.ts

Get for new user subscriptions endpoint https://github.com/lensapp/lenscloud/blob/35c4602b4abdfaa5be95893b470e34c08644bae6/backend/src/modules/user/user-subscriptions.controller.ts#L115

Get user subscriptions sets

---

integration-test/SpaceService.test.ts
src/BusinessService.ts
src/SpaceService.ts

Related API PR: https://github.com/lensapp/lenscloud/pull/2107

add BusinessService.acceptBusinessInvitation method

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2166

Add external: boolean to LBID

---

src/BusinessService.ts

Add a method to delete/withdraw a business invitation

Delete business invitation

---

package.json

Change target to js

---

package-lock.json
package.json
tsconfig.cjs.json
tsconfig.esm.json

Reverting back to tsc to unblock development for now.
We can investigate the issue with esm in the later PRs

Revert back to tsc

---

src/BusinessService.ts

Part of https://github.com/lensapp/lenscloud/issues/2316

Allow creating business invitation with role

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2333

Add invitationCreatedAt to business user

---

src/data.ts
src/index.ts

Signed-off-by: Sebastian Malton <sebastian@malton.name>

Add endOfGracePeriod

---

src/LensPlatformClient.ts
src/UserService.ts

Add the methods for the following endpoints:
- `GET /users/:userrname/emails`
- `POST /users/:username/emails`
- `PATCH /users/:username/emails`
- `DELETE /users/:username/emails`
- `PUT /users/:username/emails/send-verification`
- `POST /users/:username/emails/verification`

Add methods for user email operations

---

src/User.test.ts
src/UserService.ts

Adding this method so we can use the same across web and extension.

Get user full name method

---

src/BusinessService.ts

SDK method for delete business user endpoin https://github.com/lensapp/lenscloud/pull/2169

Delete business user method

---

src/BusinessService.ts

Patch method for changing business user role https://github.com/lensapp/lenscloud/blob/42f644c213e547d29635c6e8fb75cd9634898275/backend/src/modules/business/business-users.controller.ts#L47

Patch business user

---

src/BusinessService.ts

- Add business user BusinessID
- Add patch method to change role

Add business user businessID. Add patch business user

---

src/BusinessService.ts

New 409 code will be added in this PR https://github.com/lensapp/lenscloud/pull/2461

Add new 409 code for creating business invitation

---

.github/workflows/publish.yml

Avoid unnecessary patch publish.

---

src/BusinessService.ts

Adding SDK method to patch seats quantity for https://github.com/lensapp/lenscloud/pull/2380

Add method to change seats  quantity

---

src/BusinessService.ts

related to https://github.com/lensapp/lenscloud/issues/2499

Add 422 to delete business user

---

src/BusinessService.ts

Adding changes to refactoring done here  https://github.com/lensapp/lenscloud/pull/2380.
Merge after BE changes are merged.

Move to new routes

---

integration-test/UserService.test.ts
src/BusinessService.ts

Adding new property to support change subscription quantity

Add pending change property

---

src/UserService.ts

SDK method to upload user avatar

Upload user avatar SDK method

---

src/BusinessService.ts

Related to https://github.com/lensapp/lenscloud/issues/2275.
We need to expose this property to display the activation link for affected businesses.

Add businessIdLiteSubscriptionId to business.

---

src/BusinessService.ts

Mainly for endpoints added in https://github.com/lensapp/lenscloud/pull/2572

Add methods for business hierarchy operations

---

src/BusinessService.ts

Method to get business billing information for business billing endpoint https://github.com/lensapp/lenscloud/pull/2679

Get business billing information method.

---

src/UserService.ts

Related to https://github.com/lensapp/lenscloud/issues/2675

Add "Image size too big" error message.

---

src/UserService.ts

Add last four digits to billing information.
Endpoint changes are coming here https://github.com/lensapp/lenscloud/pull/2690

Add lastFour to billing info

---

integration-test/UserService.test.ts
src/BusinessService.ts

Changing to support https://github.com/lensapp/lenscloud/pull/2672

Change activation-link to DELETE

---

integration-test/LensDesktopKubeService.test.ts
src/LensDesktopKubeService.ts
src/LensPlatformClient.ts

* Requires https://github.com/lensapp/lenscloud/pull/2766

Add getK0sVersions

---

src/BusinessService.ts
src/LensPlatformClient.ts
src/SSOService.ts

Methods for SSO endpoints https://github.com/lensapp/lenscloud/pull/2748

SSO and business SSO methods.

---

src/BusinessService.ts

SDK methods for https://github.com/lensapp/lenscloud/pull/2803

Update types. Add Config. Add OIDC.

---

src/BusinessService.ts

Add get and update methods for LBID features implemented by https://github.com/lensapp/lenscloud/pull/2769

Add methods for Business Features

---

src/BusinessService.ts

For https://github.com/lensapp/lenscloud/pull/2855

Add `BusinessService.createBillingPageToken()`

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2864

Add `businessService.createSubscription`

---

src/BusinessService.ts
src/SSOService.ts

SDK changes to support https://github.com/lensapp/lenscloud/pull/2841.

Change to handle. Remove loginPrefixUrl

---

src/BusinessService.ts

Add 409 error handler to business service.

Add 409 handler

---

src/BusinessService.ts
src/index.ts

Add validation regular expression for business handle.

Add handle regular expression

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2881

Add `.quantity` to the post LBID request body

---

src/BusinessService.ts

Add required fields for API change https://github.com/lensapp/lenscloud/pull/2894

Add required OIDC fields

---

src/UserService.ts

SDK for linked user accounts https://github.com/lensapp/lenscloud/pull/2928

Get user accounts SDK

---

src/UserService.ts

SDK for https://github.com/lensapp/lenscloud/pull/2936

Delete user linked account method.

---

src/SSOService.ts

SDK for https://github.com/lensapp/lenscloud/pull/2943

OIDC config method

---

src/SSOService.ts
src/index.ts

SDK for https://github.com/lensapp/lenscloud/pull/2949

Connect SSO provider SDK

---

src/BusinessService.ts

SDK for https://github.com/lensapp/lenscloud/pull/2959

SDK method for SSO activation email

---

src/UserService.ts

for https://github.com/lensapp/lenscloud/issues/2909

Add  for invoices from a child account invoice

---

src/BusinessService.ts

Closes https://github.com/lensapp/lens-platform-sdk/issues/490

Add `description` field to `BusinessFeature` type

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/2968

Add an extra state 'confirmed' for child invitation

---

integration-test/UserService.test.ts
package.json
src/UserService.ts

This PR adds newsetter property to user introduced in https://github.com/lensapp/lenscloud/pull/3051
This PR also disables e2e tests.

Add newsletter property to User interface

---

src/UserService.ts

`customFields` in `SubscriptionInfo` should be optional.

Make SubscriptionInfo.customFields optional

---

src/BusinessService.ts

Include seat info added in https://github.com/lensapp/lenscloud/pull/3543
Closes #518

Add `seats` to `business.getUsers`

---

src/BusinessService.ts

Add Create/List/Delete methods for the SCIM token entity.

Add SCIM token operation methods

---

src/UserService.ts

https://github.com/lensapp/lenscloud/blob/44a6b4c3ae399834ede9d33d1206bee968b7427a/backend/src/modules/user/user-subscription-seats.controller.ts#L93

Deactivate subscription seat endpoint should be PATCH

---

.github/workflows/dependabot-test.yaml
.github/workflows/test.yaml
integration-test/DemoClusterService.test.ts
integration-test/TeamService.test.ts
jest.integration-test.config.js
src/DemoClusterService.ts
src/LensPlatformClient.ts

* Requires https://github.com/lensapp/lens-platform-sdk/pull/551
* Cherry pick this feature to release/v12 branch

feat: demo cluster api (#550)

---

integration-test/UserService.test.ts
src/BusinessService.ts

this field is added in https://github.com/lensapp/lenscloud/pull/4174

feat: add reseller flag to business entity

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/4186

Add `automaticSeatAssignment` attribute to LBID

---

src/BusinessService.ts

the info should be in `{ business: { ... } }`

fix: missing sub key of BusinessInvitationWithBusinessInfo

---

src/UserService.ts

https://github.com/lensapp/lenscloud/pull/4446 returns emailAddress property.

Add emailAddress to UserAuthMethod interface

---

src/BusinessService.ts

for https://github.com/lensapp/lenscloud/pull/4541

feat: add business.autoAcceptJoinRequests

---

src/BusinessService.ts
src/UserService.ts

For https://github.com/lensapp/lenscloud/pull/4543

feat: add business.emailDomain and business. emailDomainMatchingEnabled

---

src/data.ts
src/index.ts

See https://github.com/lensapp/lens-desktop-monorepo/issues/1240

Remove grace period

---

src/BusinessService.ts
src/index.ts

This PR adds support for new managed domains endpoints

feat: add support for managed domains
